// bot-data.js
const botQA = [
    // --- Category 1: General & Capabilities ---
    { question: "what is an ai customer assistant", answer: "An AI assistant is a smart chatbot that uses Natural Language Processing to interact with users like a human." },
    { question: "different from a standard chatbot", answer: "Yes. Standard bots follow a rigid script; this AI understands intent and handles conversational context." },
    { question: "24/7", answer: "Yes, it provides round-the-clock support without breaks or delays." },
    { question: "languages", answer: "It is multilingual, supporting English, Malayalam, Hindi, Arabic, and 50+ other languages." },
    { question: "multiple customers", answer: "Yes, it can manage thousands of simultaneous conversations without slowing down." },
    { question: "sound like a robot", answer: "No, the responses are generated to be natural, empathetic, and professional." },
    { question: "images and videos", answer: "Yes, it can share product photos, demo videos, and links." },
    { question: "mobile-friendly", answer: "Yes, the chat interface is fully responsive on all devices." },
    { question: "typos", answer: "Yes, AI understands the meaning even if the user makes spelling or grammar mistakes." },
    { question: "past interactions", answer: "Within a session, it remembers what was said earlier to provide relevant follow-up answers." },
    { question: "existing website", answer: "Yes, it requires just one line of code to be embedded." },
    { question: "manual updates", answer: "No, once trained, it uses its knowledge base to answer. You only update it when your business info changes." },
    { question: "name", answer: "Yes, if the user is logged in or provides their name, the bot uses it." },
    { question: "limit", answer: "No, it can be trained on thousands of pages of information." },
    { question: "jokes", answer: "Yes, we can enable 'Small Talk' to make the bot more engaging." },

    // --- Category 2: Business & Sales ---
    { question: "book appointments", answer: "Yes, it integrates with Google Calendar or Calendly to schedule meetings." },
    { question: "generate leads", answer: "Yes, it captures names, emails, and phone numbers during the chat." },
    { question: "take orders", answer: "Yes, it can guide users through a product catalog and take order details." },
    { question: "process payments", answer: "Yes, by providing secure links to Stripe, PayPal, or Razorpay." },
    { question: "track orders", answer: "Yes, if integrated with your database, it can give real-time order status." },
    { question: "cross-selling", answer: "Yes, it can suggest related products based on user interest." },
    { question: "discount codes", answer: "Yes, it can offer coupons to users who are about to leave the site." },
    { question: "refund policies", answer: "Yes, it can clearly state your terms and conditions." },
    { question: "surveys", answer: "Yes, it can ask for feedback or ratings after a conversation." },
    { question: "seo", answer: "Indirectly, yes, by increasing the time users spend on your website." },
    { question: "negotiations", answer: "It can be programmed with specific logic for discounts or bulk pricing." },
    { question: "pdf brochures", answer: "Yes, it can provide direct download links for files." },
    { question: "real estate", answer: "Yes, by showing property listings and booking visits." },
    { question: "restaurants", answer: "Yes, by showing menus and taking table reservations." },
    { question: "healthcare", answer: "Yes, for booking consultations and answering general health FAQs." },
    { question: "bounce rates", answer: "Yes, by engaging visitors immediately when they land on your page." },
    { question: "hot lead", answer: "Yes, it can send an instant email/SMS when a high-value lead is chatting." },
    { question: "compare products", answer: "Yes, it can list the differences between two items for the user." },
    { question: "e-commerce", answer: "Yes, it integrates with platforms like Shopify and WooCommerce." },
    { question: "complaints", answer: "Yes, it can log a complaint and provide a ticket number." },

    // --- Category 3: Technical & Integration ---
    { question: "ai models", answer: "I use GPT-4, Gemini Pro, or Claude depending on the use case." },
    { question: "whatsapp", answer: "Yes, via the WhatsApp Business API." },
    { question: "instagram", answer: "Yes, for automated DM management." },
    { question: "secure", answer: "Yes, we use industry-standard encryption for all data handling." },
    { question: "hosted", answer: "Usually on secure cloud servers like AWS, Google Cloud, or Azure." },
    { question: "crm", answer: "Yes, it integrates with HubSpot, Salesforce, Zoho, etc." },
    { question: "apis", answer: "Yes, it can fetch data from any external API." },
    { question: "gdpr", answer: "Yes, we can set it up to respect user privacy laws." },
    { question: "train", answer: "By uploading your website URL, PDFs, and text documents." },
    { question: "location", answer: "Yes, to provide location-specific info." },
    { question: "wordpress", answer: "Yes, it is compatible with all CMS platforms." },
    { question: "webhooks", answer: "Yes, to trigger actions in other apps." },
    { question: "fast", answer: "Usually under 2 seconds." },
    { question: "token usage", answer: "It refers to the amount of data processed by the AI model." },
    { question: "offline", answer: "No, it requires an internet connection." },
    { question: "white-labeled", answer: "Yes, there will be no branding except yours." },
    { question: "voice-to-text", answer: "Yes, users can click a mic icon to speak." },
    { question: "translate", answer: "Yes, it can translate in real-time." },
    { question: "chat history", answer: "Yes, an admin dashboard allows you to view all logs." },
    { question: "turn it off", answer: "Yes, you have full control over its availability." },

    // --- Category 4: UI & UX ---
    { question: "color", answer: "Yes, to match your brand's theme." },
    { question: "use my logo", answer: "Yes, the bot icon can be your brand logo." },
    { question: "typing", answer: "Yes, it shows 'Typing...' to feel more human." },
    { question: "emojis", answer: "Yes, it uses emojis to keep the tone friendly." },
    { question: "full-page chat", answer: "Yes, or a small bubble in the corner." },
    { question: "proactively start", answer: "Yes, it can greet users after a set time." },
    { question: "multiple-choice", answer: "Yes, for quick navigation." },
    { question: "dark mode", answer: "Yes, it can switch based on preference." },
    { question: "map", answer: "Yes, it can embed Google Maps links." },
    { question: "verify otps", answer: "Yes, for secure access." },
    { question: "popular questions", answer: "Yes, as Quick Reply buttons." },
    { question: "accessible", answer: "Yes, it is compatible with screen readers." },
    { question: "file uploads", answer: "Yes, users can upload images or PDFs." },
    { question: "slow internet", answer: "Yes, it is optimized for low-bandwidth." },
    { question: "triggered by buttons", answer: "Yes, specific buttons can open the bot." },
    { question: "progress bar", answer: "Yes, for long onboarding processes." },
    { question: "custom fonts", answer: "Yes, to match your typography." },
    { question: "hidden", answer: "Yes, you choose where it appears." },
    { question: "search bar", answer: "It acts like a search, but is more conversational." },
    { question: "how-to steps", answer: "Yes, it provides clear instructions." },

    // --- Category 5: Advanced AI ---
    { question: "sentiment analysis", answer: "The bot detects user mood and changes its tone." },
    { question: "human handoff", answer: "Transferring the chat to a real person when needed." },
    { question: "hallucination", answer: "When AI makes up facts; I use grounding to prevent this." },
    { question: "math problems", answer: "Yes, it has advanced reasoning capabilities." },
    { question: "write code", answer: "Yes, it can assist with technical snippets." },
    { question: "summarize", answer: "Yes, it can summarize long texts." },
    { question: "learn", answer: "It can be set to improve over time based on feedback." },
    { question: "ambiguous", answer: "It asks clarifying questions to understand better." },
    { question: "guardrails", answer: "Safety filters to prevent offensive content." },
    { question: "execute logic", answer: "Yes, like calculating a loan EMI." },
    { question: "external tools", answer: "Yes, through Function Calling." },
    { question: "context aware", answer: "Yes, it remembers the user's name during the chat." },
    { question: "detect sarcasm", answer: "Advanced models are good at identifying tone." },
    { question: "citations", answer: "Yes, it can link to the source of information." },
    { question: "generate images", answer: "Yes, if integrated with image models." },

    // --- Category 6: Pricing & Future ---
    { question: "cost of setup", answer: "It depends on complexity (Basic vs Advanced)." },
    { question: "monthly fees", answer: "Yes, for AI model usage and maintenance." },
    { question: "trial", answer: "Yes, I can set up a basic demo for your business." },
    { question: "training period", answer: "Usually 24-48 hours for data ingestion." },
    { question: "website content changes", answer: "The bot can auto-sync with your site daily." },
    { question: "technical support", answer: "Yes, I offer ongoing maintenance packages." },
    { question: "dashboard", answer: "Yes, to track leads and performance." },
    { question: "multiple bots", answer: "Yes, like separate Sales and Support bots." },
    { question: "get started", answer: "Just share your website URL and goals with me!" },
    { question: "why choose your service", answer: "I provide custom-tailored, high-accuracy AI solutions." }
];

window.botData = botQA;
